### ISSUE TITLE
Edit of assessment sets dynamic_input and static_input to 0

### ISSUE THREAD

**Issue by jhudsy** [StefanRudvin/CodeMarkerBack#5]
As the subject says, if an assessment is edited, it seems like the fields for dynamic input (and possibly static input) in the database get set to 0, meaning that uploads of code are no longer evaluated; I can't work out where this gets set in the code...

**Comment by kdryja** [comment]
Fixed in https://github.com/StefanRudvin/CodeMarkerBack/pull/7
