### ISSUE TITLE
Assessment time not recorded

### ISSUE THREAD

**Issue by jhudsy** [StefanRudvin/CodeMarkerBack#6]
Two related issues.
- The time taken for an assessment to run always reports 0 seconds.
- There is no way to specify a maximum run-time for an assessment for it to be judged "correct".

To see the first issue, run the following
```
import time
time.sleep(5)
```

**Comment by StefanRudvin** [comment]
Hi, this was not implemented as per the requirements of the assessment last year - feel free to implement it!

**Comment by kdryja** [comment]
Fixed in #7
